// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqrzegjmorkdkywvkbrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcnplZ2ptb3JrZGt5d3ZrYnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjEzNjUsImV4cCI6MjA2NDYzNzM2NX0.O_jfX7p6zzVeuEFjFEOd1qztVEw4aTMxh9vnbzsYntw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);